[package]
name = "pong"
version = "0.1.0"
authors = ["Harsh Vishwakarma <harsh.vishwakarma@nagarro.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.120.0"
find_folder = "0.3.0"